//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoinDesktop.MoinWSRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MoinWSRef.IMoinWS")]
    public interface IMoinWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoinWS/GetCustomers", ReplyAction="http://tempuri.org/IMoinWS/GetCustomersResponse")]
        MoinClasses.Customers[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMoinWS/GetCustomers", ReplyAction="http://tempuri.org/IMoinWS/GetCustomersResponse")]
        System.Threading.Tasks.Task<MoinClasses.Customers[]> GetCustomersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMoinWSChannel : MoinDesktop.MoinWSRef.IMoinWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MoinWSClient : System.ServiceModel.ClientBase<MoinDesktop.MoinWSRef.IMoinWS>, MoinDesktop.MoinWSRef.IMoinWS {
        
        public MoinWSClient() {
        }
        
        public MoinWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MoinWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoinWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MoinWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MoinClasses.Customers[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<MoinClasses.Customers[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
    }
}
